#
# BSD 3-Clause License
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main

  push:
    branches-ignore:
      - main

  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clean up previous run
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          find "$WORKSPACE" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Environment check
        uses: ./.github/actions/environment-check

      - name: Build
        uses: ./.github/actions/build-dvledtx

      - name: Smoke test
        uses: ./.github/actions/smoke-tests

      - name: Unit tests
        uses: ./.github/actions/unit-tests

      - name: ShellCheck
        uses: ./.github/actions/analysis/shellcheck

      - name: zizmor Scan
        uses: ./.github/actions/analysis/zizmor

      - name: cppcheck
        uses: ./.github/actions/analysis/cppcheck

      - name: Trivy Scan
        uses: ./.github/actions/analysis/trivy

      - name: checksec Analysis
        uses: ./.github/actions/analysis/checksec

      - name: Upload PR reports
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: DVLED-SW-TK-PR-${{ github.run_id }}
          path: ${{ github.workspace }}/reports/
          retention-days: 30
